FROM ghcr.io/open-education-hub/openedu_builder:0.3.1

# Install ffmpeg
RUN apt-get update && \
    apt-get install -y curl

# Install node LTS (16)
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs

# Install docusaurus
RUN npm install create-docusaurus@2.1.0

WORKDIR /content

ENTRYPOINT ["oe_builder"]
